# Corrections :
#   - Grafana 11.4.0 (8.3.0 = 2022, plein de CVE critiques)
#   - Plus de docker.sock monte (cf. docker-compose.yml)
#   - L'utilisateur grafana (uid 472) est non-root par defaut

FROM grafana/grafana:11.4.0
